Added new class based Homework version with two play modes
kevin-hausmann/Python-Tuesday pull request #1
Opened 2022-01-24 09:06 UTC by Christian-Mielke

Dear Kevin,

here is the homework from the forked repo.

Ciao for now 

Christian

2022-01-24 09:29 UTC, kevin-hausmann requested changes
Hi Christian, this all looks great, if maybe a bit over-complex. Just for fun, I put a few extra challenges for you to work on. (But you do not have to, I consider your homework completed.)

2022-01-24 09:29 UTC, kevin-hausmann commented on Homework 02/CM/guesswork_v2.py
> +        while True:
This full `while` loop could be implemented more elegantly:

```suggestion
    while self.gametype not in options:
            self.gametype = input('Please input P for PC guestimation or H for Human guestimation!')
```

2022-01-24 09:29 UTC, kevin-hausmann commented on Homework 02/CM/guesswork_v2.py
> +        while True:
Please try to avoid `while True:` unless you have really good reasons!

2022-01-24 09:29 UTC, kevin-hausmann commented on Homework 02/CM/guesswork_v2.py
> +        while True:
Same here. This whole `while` and nested `if else` construct feels verbose and overly complicated, can you try to refactor this and make it shorter and more readable?

2022-01-24 09:45 UTC, kevin-hausmann commented
Also, just as a side note: you should be able to directly push a branch to this repo, there is no need for you to create a fork (I hope)

2022-01-27 06:20 UTC, kevin-hausmann commented
Hey @Christian-Mielke - will you work on this? If not, I would just merge it as is....

2022-01-31 10:00 UTC, Christian-Mielke commented
Changed the while true, removed breakpoints and reduced the verbosity a bit.

2022-01-31 11:27 UTC, kevin-hausmann approved these changes

2022-01-31 12:42 UTC, kevin-hausmann commented
Hi Christian, please merge this PR instead of closing it - thanks!

2022-01-31 12:54 UTC, Christian-Mielke commented
I have no write access. Can you please resend the invitation, please?

2022-01-31 12:58 UTC, kevin-hausmann commented
Resent

2022-01-31 13:11 UTC, merged