this is the second homework (number guessing game inverse)
kevin-hausmann/Python-Tuesday pull request #2
Opened 2022-01-24 11:20 UTC by AnnaZagorski

Please give me a feedback if you like!

2022-01-24 13:33 UTC, kevin-hausmann requested changes
Good start Anna! I put some comments, feel free to respond or improve your code, if you can.

2022-01-24 13:33 UTC, kevin-hausmann commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +guess = int(randint(1, 5))# vom Computer geratene Zahl
This line repeats all over the program, please try to make the code more concise!

2022-01-24 13:33 UTC, kevin-hausmann commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +    if guess > entry:
Two of three lines of both the `if` and the `elif` branch are identical. We want to avoid this kind of copy&paste code. Only use the `if` part for code that is actually different.

2022-01-24 13:33 UTC, kevin-hausmann commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +entry = int(input(f"Hallo, {name}, bitte eine Zahl zwischen 1 und 5 eingeben: "))
Why only 1 to 5, those are very few options?

2022-01-24 13:33 UTC, kevin-hausmann commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +        guess = int(randint(1, 5))# vom Computer geratene Zahl
Can the computer guess more cleverly?

2022-01-24 13:33 UTC, kevin-hausmann commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +    guess = int(randint(1, 5))# vom Computer geratene Zahl
The line would be executed, even if the correct number has already been guessed, right? That should not happen!

2022-01-28 07:16 UTC, closed without merging

2022-01-28 07:39 UTC, AnnaZagorski commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +    guess = int(randint(1, 5))# vom Computer geratene Zahl
Yes, that's true, of course

2022-01-28 07:39 UTC, AnnaZagorski commented on Homework 02/AZ/2.Aufgabe_23.01.22.py
> +    if guess > entry:
not sure what is meant by copy&paste code